// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7iQW-tCquHCL6mWvbz3twG2a8FsOXw1E',
    appId: '1:491035289469:web:fb19f093bab88be2a34e14',
    messagingSenderId: '491035289469',
    projectId: 'croplyai',
    authDomain: 'croplyai.firebaseapp.com',
    storageBucket: 'croplyai.firebasestorage.app',
    measurementId: 'G-WDRPR233V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkMiJLlsnr9FWwvbdYYElLQIwnzham7cY',
    appId: '1:491035289469:android:8f112816850a19e5a34e14',
    messagingSenderId: '491035289469',
    projectId: 'croplyai',
    storageBucket: 'croplyai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK2w2JtXHRBIKvfEWYgqCCCYZ3YEfosfU',
    appId: '1:491035289469:ios:4245dbb4eed9aa23a34e14',
    messagingSenderId: '491035289469',
    projectId: 'croplyai',
    storageBucket: 'croplyai.firebasestorage.app',
    iosBundleId: 'com.example.croplyAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK2w2JtXHRBIKvfEWYgqCCCYZ3YEfosfU',
    appId: '1:491035289469:ios:4245dbb4eed9aa23a34e14',
    messagingSenderId: '491035289469',
    projectId: 'croplyai',
    storageBucket: 'croplyai.firebasestorage.app',
    iosBundleId: 'com.example.croplyAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7iQW-tCquHCL6mWvbz3twG2a8FsOXw1E',
    appId: '1:491035289469:web:ff2b1e0af381710ba34e14',
    messagingSenderId: '491035289469',
    projectId: 'croplyai',
    authDomain: 'croplyai.firebaseapp.com',
    storageBucket: 'croplyai.firebasestorage.app',
    measurementId: 'G-WCBMR7VHWD',
  );
}